name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'
    
    - name: Test pipz core
      run: |
        go test -v -race -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out
    
    - name: Test examples package
      working-directory: ./examples
      run: |
        go test -v ./...
    
    - name: Test benchmarks package
      working-directory: ./benchmarks
      run: |
        go test -v ./...
    
    - name: Run benchmarks
      working-directory: ./benchmarks
      run: |
        go test -bench=. -benchmem -benchtime=100ms
    
    - name: Demo compilation check
      working-directory: ./demo
      run: |
        go build -o demo .