name: Update Changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - '.github/workflows/release.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    name: Update CHANGELOG.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for changelog generation
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: Install svu
      run: go install github.com/caarlos0/svu@latest
    
    - name: Get current version
      id: current_version
      run: |
        CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $CURRENT_VERSION"
    
    - name: Calculate next version
      id: next_version
      run: |
        NEXT_VERSION=$(svu next)
        echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT
        echo "Next version will be: $NEXT_VERSION"
    
    - name: Update Unreleased section
      run: |
        # Get commits since last tag
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        
        # Create temporary file for new entries
        echo "" > new_entries.md
        
        # Group commits by type
        echo "### Added" >> new_entries.md
        git log --pretty=format:"- %s" ${LAST_TAG:+$LAST_TAG..}HEAD | grep -E "^(feat|add):" | sed 's/^feat: /- /' | sed 's/^add: /- /' >> new_entries.md || true
        
        echo "" >> new_entries.md
        echo "### Changed" >> new_entries.md
        git log --pretty=format:"- %s" ${LAST_TAG:+$LAST_TAG..}HEAD | grep -E "^(change|update|refactor):" | sed 's/^change: /- /' | sed 's/^update: /- /' | sed 's/^refactor: /- /' >> new_entries.md || true
        
        echo "" >> new_entries.md
        echo "### Fixed" >> new_entries.md
        git log --pretty=format:"- %s" ${LAST_TAG:+$LAST_TAG..}HEAD | grep -E "^(fix|bugfix):" | sed 's/^fix: /- /' | sed 's/^bugfix: /- /' >> new_entries.md || true
        
        echo "" >> new_entries.md
        echo "### Security" >> new_entries.md
        git log --pretty=format:"- %s" ${LAST_TAG:+$LAST_TAG..}HEAD | grep -E "^(security|sec):" | sed 's/^security: /- /' | sed 's/^sec: /- /' >> new_entries.md || true
        
        echo "" >> new_entries.md
        
        # Clean up empty sections
        sed -i '/^### Added$/,/^### /{/^### Added$/d; /^### /!d;}' new_entries.md
        sed -i '/^### Changed$/,/^### /{/^### Changed$/d; /^### /!d;}' new_entries.md
        sed -i '/^### Fixed$/,/^### /{/^### Fixed$/d; /^### /!d;}' new_entries.md
        sed -i '/^### Security$/,/^$/{/^### Security$/d; /^$/!d;}' new_entries.md
        
        # Remove multiple empty lines
        sed -i '/^$/N;/^\n$/d' new_entries.md
    
    - name: Update CHANGELOG.md
      run: |
        # Find where the Unreleased section content starts
        UNRELEASED_LINE=$(grep -n "^## \[Unreleased\]" CHANGELOG.md | cut -d: -f1)
        
        if [ -n "$UNRELEASED_LINE" ]; then
          # Find the next section (next version or end of file)
          NEXT_SECTION_LINE=$(tail -n +$((UNRELEASED_LINE + 1)) CHANGELOG.md | grep -n "^## \[" | head -1 | cut -d: -f1)
          
          if [ -n "$NEXT_SECTION_LINE" ]; then
            # Calculate actual line number
            NEXT_SECTION_LINE=$((UNRELEASED_LINE + NEXT_SECTION_LINE))
            
            # Extract everything before Unreleased content
            head -n $((UNRELEASED_LINE)) CHANGELOG.md > temp_changelog.md
            echo "" >> temp_changelog.md
            
            # Add new entries
            cat new_entries.md >> temp_changelog.md
            
            # Add everything after the Unreleased section
            tail -n +$((NEXT_SECTION_LINE)) CHANGELOG.md >> temp_changelog.md
          else
            # No other versions, just append
            head -n $((UNRELEASED_LINE)) CHANGELOG.md > temp_changelog.md
            echo "" >> temp_changelog.md
            cat new_entries.md >> temp_changelog.md
          fi
          
          mv temp_changelog.md CHANGELOG.md
        fi
    
    - name: Check if changes were made
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add CHANGELOG.md
        git commit -m "chore: update CHANGELOG.md [skip ci]"
        git push